<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WKWIN6590441" name="com.guru.banking.LoginToBank" tests="3" failures="0" timestamp="27 Jul 2018 06:34:33 GMT" time="6.021" errors="1">
  <testcase name="loginBankSucces" time="4.562" classname="com.guru.banking.LoginToBank"/>
  <testcase name="closebrowser" time="1.459" classname="com.guru.banking.LoginToBank"/>
  <testcase name="loginFailure" time="0.000" classname="com.guru.banking.LoginToBank">
    <error type="org.testng.TestNGException" message="
Method public void com.guru.banking.LoginToBank.loginFailure(java.lang.String,java.lang.String) throws java.io.IOException requires a @DataProvider named : getInvalidDataee in class com.guru.bankingutils.ReusableMethods">
      <![CDATA[org.testng.TestNGException: 
Method public void com.guru.banking.LoginToBank.loginFailure(java.lang.String,java.lang.String) throws java.io.IOException requires a @DataProvider named : getInvalidDataee in class com.guru.bankingutils.ReusableMethods
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- loginFailure -->
</testsuite> <!-- com.guru.banking.LoginToBank -->
